name = "SubspacePreservingSparsification"
uuid = "4d1ea0e1-70d2-4753-baf0-722475fae2d0"
authors = ["Matt1h <m.holzenkamp@web.de> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["MAT", "Test", "DelimitedFiles", "Random", "BenchmarkTools", "ProfileView"]
